# Homework 4

## Mysql-Python Connection

In [2]:
import mysql.connector
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import csv

%matplotlib inline

In [3]:
db_connection = mysql.connector.connect(
  host="localhost",
  user="root",
  passwd="testPass", 
  auth_plugin='mysql_native_password'
)
print(db_connection)

<mysql.connector.connection.MySQLConnection object at 0x7f8d64e1cc70>

In [4]:
# creating database_cursor to perform SQL operation to run queries
db_cursor = db_connection.cursor(buffered=True)

# executing cursor with execute method and pass SQL query
db_cursor.execute("CREATE DATABASE movie_db")

# get list of all databases
db_cursor.execute("SHOW DATABASES")

# print all databases
for db in db_cursor:
    print(db)
    
db_cursor.execute("USE movie_db")

('information_schema',)
('movie_db',)
('mysql',)
('performance_schema',)
('sys',)

## Load Data to Mysql Tables

In [5]:



import csv
from mysql.connector import IntegrityError

#Language ıcın 
def populate_table1(db_connection, db_cursor, insert_query, csv_file):
    with open(csv_file, 'r', newline='') as file:
         

        for line in file:
            row = line.strip().split(';')

            imdb_id = row[0].strip() if row[0] else None
            language = row[1].strip() if row[1] else None
            country = row[2].strip() if row[2] else None

            #print(f"Inserting row: {imdb_id}, {language}, {country}")

            try:
                db_cursor.execute(insert_query, (imdb_id, language, country))
            except mysql.connector.IntegrityError:
                update_query = "UPDATE LANGUAGE_FINAL15 SET language = %s, country = %s WHERE imdb_id = %s"
                db_cursor.execute(update_query, (imdb_id, language, country))

    db_connection.commit()

#Movıe ıcın
def populate_table2(db_connection, db_cursor, insert_query, csv_file):
    with open(csv_file, 'r', newline='') as file:
        csv_data = csv.reader(file, delimiter=';')
        next(csv_data)  # Skip the header row

        for row in csv_data:
            row = [item.strip() if item else None for item in row]  # Remove leading/trailing whitespaces

            imdb_id, title, year, rating, runtime, genre, released, awards, lastupdated, type = row

            #print(f"Inserting row: {imdb_id}, {title}, {year}, {rating}, {runtime}, {genre}, {released}, {awards}, {lastupdated}, {type}")

            try:
                db_cursor.execute(insert_query, (imdb_id, title, year, rating, runtime, genre, released, awards, lastupdated, type))
            except mysql.connector.IntegrityError:
                continue

    db_connection.commit()

#Crıtıc movıe detaıl
def populate_table3(db_connection, db_cursor, insert_query, csv_file):
    with open(csv_file, 'r', newline='') as file:
         
        for line in file:
            row = line.strip().split(';')

            critic_id = row[0].strip() if row[0] else None
            imdb_rating = row[1].strip() if row[1] else None
            imdbVotes = row[2].strip() if row[2] else None

            #print(f"Inserting row: {critic_id}, {imdb_rating}, {imdbVotes}")

            try:
                db_cursor.execute(insert_query, (critic_id, imdb_rating, imdbVotes))
            except mysql.connector.IntegrityError:
                update_query = "UPDATE CRITICS_DETAIL SET critic_id = %s, imdb_rating = %s ,imdbVotes = %s"
                db_cursor.execute(update_query, (critic_id, imdb_rating, imdbVotes))
    db_connection.commit()


#crıtıc relatıon ıcıın
def populate_table4(db_connection, db_cursor, insert_query, csv_file):
    with open(csv_file, 'r', newline='') as file:
         
        for line in file:
            row = line.strip().split(';')

            imdbID = row[0].strip() if row[0] else None
            critic_id = row[1].strip() if row[1] else None
    

            #print(f"Inserting row: {imdbID}, {critic_id}")

            try:
                db_cursor.execute(insert_query, (imdbID, critic_id))
            except mysql.connector.IntegrityError:
                update_query = "UPDATE CRITICS_MAIN SET imdbID = %s, critic_id = %s "
                db_cursor.execute(update_query, (imdbID, critic_id))
    db_connection.commit()




#story relatıon ıcın 
def populate_table5(db_connection, db_cursor, insert_query, csv_file):
    with open(csv_file, 'r', newline='') as file:
         
        for line in file:
            row = line.strip().split(';')

            imdbID = row[0].strip() if row[0] else None
            storyID = row[1].strip() if row[1] else None
    

            #print(f"Inserting row: {imdbID}, {storyID}")

            try:
                db_cursor.execute(insert_query, (imdbID, storyID))
            except mysql.connector.IntegrityError:
                update_query = "UPDATE STORY_MAIN SET imdbID = %s, storyID = %s "
                db_cursor.execute(update_query, (imdbID, storyID))
    db_connection.commit()



#story detaıl ıcın 
def populate_table6(db_connection, db_cursor, insert_query, csv_file):
    with open(csv_file, 'r', newline='') as file:
         
        for line in file:
            row = line.strip().split(';')

            storyID = row[0].strip() if row[0] else None
            poster = row[1].strip() if row[1] else None
            plot = row[2].strip() if row[2] else None
            fullplot = row[2].strip() if row[2] else None

            #print(f"Inserting row: {storyID}, {poster} ,{plot}, {fullplot}  ")

            try:
                db_cursor.execute(insert_query, (storyID, poster ,plot,fullplot))
            except mysql.connector.IntegrityError:
                update_query = "UPDATE STORY_DETAIL SET storyID = %s, poster = %s ,plot = %s,fullplot = %s "
                db_cursor.execute(update_query, (storyID, poster ,plot,fullplot))
    db_connection.commit()



#CAST DETAIL
def populate_table7(db_connection, db_cursor, insert_query, csv_file):
    with open(csv_file, 'r', newline='', encoding='utf-8') as file:

         
        for line in file:
            row = line.strip().split(';')

            castID = row[0].strip() if row[0] else None
            cast = row[1].strip() if row[1] else None
            writer = row[2].strip() if row[2] else None
            director = row[2].strip() if row[2] else None

            #print(f"Inserting row: {castID}, {cast} ,{writer}, {director}  ")

            try:
                db_cursor.execute(insert_query, (castID, cast ,writer,director))
            except mysql.connector.IntegrityError:
                update_query = "UPDATE CAST_DETAIL SET storyID = %s, cast = %s ,writer = %s,director = %s "
                db_cursor.execute(update_query, (castID, cast ,writer,director))
    db_connection.commit()


#MOVİE CAST
def populate_table8(db_connection, db_cursor, insert_query, csv_file):
    with open(csv_file, 'r', newline='') as file:
         
        for line in file:
            row = line.strip().split(';')

            imdbID = row[0].strip() if row[0] else None
            castID = row[1].strip() if row[1] else None
    

            #print(f"Inserting row: {imdbID}, {castID}")

            try:
                db_cursor.execute(insert_query, (imdbID, castID))
            except mysql.connector.IntegrityError:
                update_query = "UPDATE CAST_RELATION SET imdbID = %s, castID = %s "
                db_cursor.execute(update_query, (imdbID, castID))
    db_connection.commit()

In [6]:
db_cursor.execute("""
    CREATE TABLE LANGUAGE_FINAL15 (
        imdb_ID VARCHAR(45) PRIMARY KEY,
        language VARCHAR(255),
        country VARCHAR(255)
    )
""")

insert_movie = (
    "INSERT INTO LANGUAGE_FINAL15(imdb_id, language, country) "
    "VALUES (%s, %s, %s)"
)

populate_table1(db_connection, db_cursor, insert_movie, "LanguageMovie.csv")

In [7]:
db_cursor.execute("""
  CREATE TABLE MOVIEFINAL (
  imdb_id VARCHAR(45) PRIMARY KEY,
  title VARCHAR(255),
  year VARCHAR(255),
  rating VARCHAR(255),
  runtime VARCHAR(255),
  genre VARCHAR(255),
  released VARCHAR(255),
  awards VARCHAR(255),
  last_updated VARCHAR(255),
  type VARCHAR(45)
)
""")
                  
insert_movies = (
    "INSERT INTO MOVIEFINAL(imdb_id, title, year,rating,	runtime,	genre,	released,	awards,	last_updated,	type) "
    "VALUES (%s, %s, %s,%s,%s,%s, %s, %s,%s,%s)"
)

populate_table2(db_connection, db_cursor, insert_movies, "Movie.csv")

In [8]:
db_cursor.execute("""CREATE TABLE  CRITIC_RELATION3 (
    imdb_id VARCHAR(45),
    critic_ID VARCHAR(10),
    INDEX idx_cast_ID (critic_ID),
    FOREIGN KEY (imdb_id) REFERENCES MOVIEFINAL(imdb_id)
)""")

insert_critic = (
    "INSERT INTO CRITIC_RELATION3(imdb_id, critic_ID) "
    "VALUES (%s, %s)"
)

populate_table4(db_connection, db_cursor, insert_critic, "movieCritict.csv")

In [9]:
db_cursor.execute("""CREATE TABLE  STORY_RELATION3 (
    imdb_id VARCHAR(45),
    story_ID VARCHAR(10),
    INDEX idx_story_ID (story_ID),
    FOREIGN KEY (imdb_id) REFERENCES MOVIEFINAL(imdb_id)
)""")

insert_story = (
    "INSERT INTO STORY_RELATION3(imdb_id, story_ID) "
    "VALUES (%s, %s)"
)

populate_table5(db_connection, db_cursor, insert_story, "MovieStory.csv")

In [10]:
#db_cursor.execute("""CREATE TABLE  CAST_RELATION3 (
 #   imdb_id VARCHAR(10),
  #  cast_ID VARCHAR(10),
   # FOREIGN KEY (imdb_id) REFERENCES MOVIEFINAL(imdb_id)
#)""")

#insert_orderpayments = (
 #   "INSERT INTO CAST_RELATION3(imdb_id, cast_ID) "
  #  "VALUES (%s, %s)"
#)

#populate_table8(db_connection, db_cursor, insert_orderpayments, "MovieCast.csv")


db_cursor.execute("""CREATE TABLE CAST_RELATION4 (
    imdb_id VARCHAR(45),
    cast_ID VARCHAR(10),
    INDEX idx_cast_ID (cast_ID),
    FOREIGN KEY (imdb_id) REFERENCES MOVIEFINAL(imdb_id)
)""")

insert_orderpayments = (
    "INSERT INTO CAST_RELATION4(imdb_id, cast_ID) "
    "VALUES (%s, %s)"
)

populate_table8(db_connection, db_cursor, insert_orderpayments, "MovieCast.csv")

In [11]:
#db_cursor.execute("""CREATE TABLE  CAST_DETAIL2 (
 #   cast_ID VARCHAR(10),
  #  cast VARCHAR(500),
   # writer VARCHAR(50),
    #director VARCHAR(50),

    #FOREIGN KEY (cast_ID) REFERENCES CAST_RELATION3(cast_ID)
#)""")

#insert_castd = (
 #   "INSERT INTO CAST_DETAIL2(cast_ID, cast,writer,director) "
  #  "VALUES (%s, %s)"
#)

#populate_table4(db_connection, db_cursor, insert_castd, "CastDetail.csv")

db_cursor.execute("""CREATE TABLE CAST_DETAIL8 (
    cast_ID VARCHAR(10),
    cast VARCHAR(5000),
    writer VARCHAR(5000),
    director VARCHAR(5000),
    FOREIGN KEY (cast_ID) REFERENCES CAST_RELATION4(cast_ID)
)""")

insert_castd = (
    "INSERT INTO CAST_DETAIL8(cast_ID, cast, writer, director) "
    "VALUES (%s, %s, %s, %s)"
)

populate_table7(db_connection, db_cursor, insert_castd, "CastDetail.csv")

In [12]:
db_cursor.execute("""CREATE TABLE STORY_DETAIL4 (
    story_ID VARCHAR(10),
    poster VARCHAR(5000),
    plot VARCHAR(5000),
    fullplot VARCHAR(5000),
    FOREIGN KEY (story_ID) REFERENCES STORY_RELATION3(story_ID)
)""")

insert_storyd = (
    "INSERT INTO STORY_DETAIL4(story_ID, poster, plot, fullplot) "
    "VALUES (%s, %s, %s, %s)"
)

populate_table7(db_connection, db_cursor, insert_storyd, "StoryMovieDetail.csv")

In [13]:
db_cursor.execute("""CREATE TABLE CRITIC_DETAIL2 (
    critic_ID VARCHAR(10),
    imdbRating VARCHAR(50),
    imdbVotes VARCHAR(50),
    FOREIGN KEY (critic_ID) REFERENCES CRITIC_RELATION3(critic_ID)
)""")

insert_criticd = (
    "INSERT INTO CRITIC_DETAIL2(critic_ID, imdbRating, imdbVotes) "
    "VALUES (%s, %s, %s)"
)

populate_table3(db_connection, db_cursor, insert_criticd, "CrititcMovieDetail.csv")